name: Python Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "0 18 * * *" # Run at 6:00 PM UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROXY_URL: ${{ vars.PROXY_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run tests
        run: pytest

      - name: Upload Scrapy Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scrapy-test-log
          path: test-run.log

      - name: Notify Slack on failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ vars.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"⚠️ Python tests failed in the GitHub Actions workflow for repository: ${{ github.repository }}. Branch: ${{ github.ref }}. Check the workflow here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
          ${{ vars.SLACK_WEBHOOK_URL }}
